main/urls.py
from django.urls import path
# new impor tugas 3
from main.views import show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id
# new impor tugas 4
from main.views import register, login_user, logout_user #sesuaikan dengan nama fungsi yang dibuat
from main.views import add_item, reduce_item, delete_item
# new impor tugas 5
from main.views import edit_item
from django.conf import settings
from django.conf.urls.static import static
# new impor tugas 6
from main.views import add_product_ajax, get_product_json, delete_item_ajax
# new impor tugas 9
from main.views import create_product_flutter


app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    # new path tugas 3
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    # new path tugas 4
    path('register/', register, name='register'), #sesuaikan dengan nama fungsi yang dibuat
    path('login/', login_user, name='login'), #sesuaikan dengan nama fungsi yang dibuat
    path('logout/', logout_user, name='logout'),
    path('add_item/<int:id>/', add_item, name='add_item'),
    path('reduce_item/<int:id>/', reduce_item, name='reduce_item'),
    path('delete_item/<int:id>/', delete_item, name='delete_item'),
    # new path tugas 5
    path('edit-item/<int:id>', edit_item, name='edit_item'),
    # new path tugas 6
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete_item_ajax/', delete_item_ajax, name='delete_item_ajax'),
    # new path tugas 9
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

restaurant_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.core.validators import FileExtensionValidator

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=255)
    # amount = models.IntegerField(default = 10)
    description = models.TextField() 
    # kalau dikasih parameter blank & null itu tidak wajib diisi
    price = models.PositiveIntegerField(default = 20000)
    date_added = models.DateField(auto_now_add=True)
    # === tugas 4
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # Tambahkan field amount untuk menyimpan jumlah stok
    amount = models.PositiveIntegerField(default=10)
    # === tugas 5
    # Tambahkan field gambar
    # image = models.ImageField(upload_to='item_images/', validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])], blank=True, null=True)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description", "price"]

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Item
# new import tugas 3 dan 4
from django.http import HttpResponseRedirect
from main.forms import ItemForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
# new impor tugas 5
from django.db.models import Q
# new impor tugas 6
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse


# Create your views here.

@login_required(login_url='/login')
def show_main(request):
    # search_query = request.GET.get('search', '')  # Mendapatkan parameter pencarian dari query string
    items = Item.objects.filter(user=request.user)
    num_items = items.count()
    last_login = request.COOKIES.get('last_login', 'N/A')

    # Mencari daftar produk berdasarkan nama atau deskripsi yang cocok dengan query pencarian
    # items = items.filter(Q(name__icontains=search_query) | Q(description__icontains=search_query))

    context = {
        'app_name': 'Ghina27-app',
        'my_name': request.user.username,
        'my_class': 'PBP B',
        'items': items,
        'num_items': num_items,
        'last_login': last_login,
    }
    return render(request, "main.html", context)

# ========= tugas 3

@csrf_exempt
def create_item(request):
    if request.method == "POST":
        # form = ItemForm(request.POST, request.FILES) # Menggunakan request.FILES untuk menangani file gambar
        form = ItemForm(request.POST)

        if form.is_valid():
            item = form.save(commit=False)
            item.user = request.user
            item.save()
            return redirect('main:show_main')
    else:
        form = ItemForm()

    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

# ======== tugas 4

# @csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

# @csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def add_item(request, id):
    item = get_object_or_404(Item, pk=id)

    if item.amount >= 0:  # Tambahkan pengecekan stok tidak kurang dari 0
        item.amount += 1
        item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def reduce_item(request, id):
    item = get_object_or_404(Item, pk=id)

    if item.amount > 0: # Tambahkan pengecekan stok tidak kurang dari 1
        item.amount -= 1
        item.save()
    return HttpResponseRedirect(reverse('main:show_main'))

def delete_item(request, id):
    # Get data berdasarkan ID
    item = Item.objects.get(pk = id)
    item.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def edit_item(request, id):
    item = get_object_or_404(Item, pk=id)
    if request.method == "POST":
        # form = ItemForm(request.POST, request.FILES, instance=item) # Menggunakan request.FILES untuk menangani file gambar
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:show_main'))
    else:
        form = ItemForm(instance=item)
    
    context = {'form': form, 'item': item}
    return render(request, "edit_item.html", context)

def get_product_json(request):
    product_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))


#========= tugas 6

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        price = request.POST.get("price")
        amount = request.POST.get("amount")

        user = request.user

        new_product = Item(name=name, amount=amount, description=description, price=price, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")

        item = Item.objects.filter(name=name)
        item.delete()

        return HttpResponse(b"DELETED", status=201)

    return HttpResponseNotFound()

#========= tugas 9

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %}

{% block content %}
<style>
    body {
        background-color: #e1f1f5;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .card {
        background-color: #c2e2ec;
        border-color: #d1e9f1;
        width: 400px;
        margin: 0 auto; /* Ini akan menggeser card ke tengah secara horizontal */
    }

    .card-title {
        color: #000;
    }

    .btn-primary {
        background-color: blue;
        border-color: blue;
    }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="card-title">Add New Item</h1>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Add Item</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_item.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<style>
    /* Warna latar belakang untuk seluruh halaman */
    body {
        background-color: #e1f1f5;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    /* Warna latar belakang card */
    .card {
        background-color: #c2e2ec;
        border-color: #d1e9f1;
        width: 400px;
        margin: 0 auto; /* Ini akan menggeser card ke tengah secara horizontal */
    }

    /* Warna teks judul card */
    .card-title {
        color: #000;
    }

    /* Warna tombol login */
    .btn-primary {
        background-color: blue;
        border-color: blue;
    }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="card-title">Edit Item</h1>
                </div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div>
                            <input type="submit" class="btn btn-primary" value="Edit Item"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-color: #e1f1f5;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .card {
        background-color: #c2e2ec;
        border-color: #d1e9f1;
        width: 400px;
        margin: 0 auto; /* Ini akan menggeser card ke tengah secara horizontal */
    }

    .card-title {
        color: #000;
    }

    .btn-primary {
        background-color: blue;
        border-color: blue;
    }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="card-title">Login</h1>
                </div>
                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" name="username" placeholder="Username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="password" placeholder="Password" class="form-control">
                        </div>
                        <div class="form-group">
                            <input class="btn btn-primary" type="submit" value="Login">
                        </div>
                    </form>
                    {% if messages %}
                        <ul class="list-unstyled">
                            {% for message in messages %}
                                <li class="text-danger">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% block content %}
<style>
    body {
        background-color: #e1f1f5;
    }
</style>

<nav class="navbar navbar-expand-lg" style="background-color: #b3dbe7;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'main:show_main' %}">Ghina27-app</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/ghina2703/ghina27-app" target="_blank">GitHub</a>
          </li>
          <li class="nav-item">
            <button type="button" class="btn btn-custom" data-bs-toggle="modal" data-bs-target="#createModal">Create Item by AJAX</button>
          </li>
          <li class="nav-item">
              <button type="button" class="btn btn-custom" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete Item by AJAX</button>
          </li>
        
        </ul>
      </div>
    </div>
</nav>

<style>
    .navbar-brand {
        font-weight: bold;
    }
    .navbar-nav .nav-link {
        font-weight: bold;
    }
    .btn-custom {
        background-color: yellow;
        border-color: rgb(0, 179, 255); 
        color: black;
    }
</style>

<div></div>
<div class="container">
    <h1 style="text-align: center;">Selamat Datang di Aplikasi {{ app_name }}</h1>

    <div style="text-align: center;">
        <h4>~ Owner ~</h4>
        <h4>Name:</h4>
        <p>{{ my_name }}</p>

        <h4>Class:</h4>
        <p>{{ my_class }}</p>
        
        <p style="font-weight: bold;" id="jml_item">Kamu menyimpan {{ num_items }} item pada aplikasi ini.</p>
        
    </div>
    
    <div class="row" id="product-container">
      <!-- Data produk akan ditampilkan di sini menggunakan AJAX GET -->
    </div>
  

    <!-- Modal untuk menambahkan produk -->
    <div class="modal fade" id="createModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
                  <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                  <form id="form_add" onsubmit="return false;">
                      {% csrf_token %}
                      <div class="mb-3">
                          <label for="name" class="col-form-label">Name:</label>
                          <input type="text" class="form-control" id="name" name="name"></input>
                      </div>
                      <div class="mb-3">
                          <label for="price" class="col-form-label">Price:</label>
                          <input type="number" class="form-control" id="price" name="price"></input>
                      </div>
                      <div class="mb-3">
                        <label for="amount" class="col-form-label">Amount:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                          <label for="description" class="col-form-label">Description:</label>
                          <textarea class="form-control" id="description" name="description"></textarea>
                      </div>
                  </form>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
              </div>
          </div>
      </div>
  </div>


    <!-- Modal untuk delete produk -->
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteProductLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteProductLabel">Delete Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="form_delete" onsubmit="return false;">
              {% csrf_token %}
              <div class="mb-3">
                  <label for="name" class="col-form-label">Nama produk:</label>
                  <input type="text" class="form-control" id="name" name="name"></input>
              </div>
            </form>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="confirmDelete" data-bs-dismiss="modal">Delete</button>
            </div>
        </div>
    </div>
  </div>


  <script>
      // Memanggil fungsi untuk mendapatkan data produk saat halaman dimuat
      refreshProducts();

      async function getProducts() {
          // Ganti URL sesuai dengan rute yang benar
          return fetch("{% url 'main:get_product_json' %}").then((res) => res.json());
      }
      // Fungsi untuk mendapatkan data produk dengan AJAX GET
          async function refreshProducts() {
          const products = await getProducts()
          document.getElementById("jml_item").innerText = `Kamu menyimpan ${products.length} item pada aplikasi ini.`

          fetch("{% url 'main:get_product_json' %}")
                .then(response => response.json())
                .then(data => {
                    const productContainer = document.getElementById("product-container");
                    productContainer.innerHTML = ""; // Menghapus data produk yang sudah ada

                    data.forEach((product, index) => { // Menggunakan forEach dengan index
                        const item = product.fields;
                        const productId = product.pk;

                        // Membuat card untuk setiap produk
                        const productCard = document.createElement("div");
                        productCard.className = "col-md-4";

                        // Bonus Tugas 5
                        if (index === data.length - 1) { // Cek jika objek adalah yang terakhir
                            productCard.classList.add("last-row");
                        }

                        productCard.innerHTML = `
                            <div class="card mb-4">
                                <div class="card-body">
                                    <h5 class="card-title">${item.name}</h5>
                                    <p class="card-text">${item.description.replace(/\n/g, '<br>')}</p>
                                </div>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">Amount: <span>${item.amount}</span></li>
                                    <div class="card-body">
                                      <a href="add_item/${product.pk}" class="btn btn-custom">+</a>
                                      <a href="reduce_item/${product.pk}" class="btn btn-custom">-</a>
                                    </div>
                                    </li>


                                    <li class="list-group-item">Price: ${item.price}</li>
                                    <li class="list-group-item">Date Added: ${item.date_added}</li>
                                </ul>

                                <div class="card-body">
                                    <a href="edit-item/${product.pk}" class="btn btn-primary">Edit</a>
                                    <a href="delete_item/${product.pk}" class="btn btn-danger">Delete</a>
                                </div>
                            </div>
                        `;
                        productContainer.appendChild(productCard);
                    });

                });
                    document.getElementById("product_table").innerHTML = htmlString
          }

      function addProduct() {
      fetch("{% url 'main:add_product_ajax' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#form_add'))
      }).then(refreshProducts)

      document.getElementById("form_add").reset()
      return false

      }
      document.getElementById("button_add").onclick = addProduct


      function deleteProduct() {
          fetch("{% url 'main:delete_item_ajax' %}", {
              method: "POST",
              body: new FormData(document.querySelector('#form_delete'))
          }).then(refreshProducts)

          document.getElementById("form_delete").reset()
          return false

      }
      document.getElementById("confirmDelete").onclick = deleteProduct

  </script>

  <style>
    .btn-custom {
        background-color: rgb(245, 245, 153);
        border-color: rgb(15, 26, 30); 
        color: black;
    }

    /* Bonus Tugas 5 */
    .last-row {
        background-color: rgb(246, 246, 181); 
    }

  </style>


  <div class="text-center">
    <a href="{% url 'main:create_item' %}" class="btn btn-primary">Add New Item</a>
    <a href="{% url 'main:logout' %}" class="btn btn-danger">Logout</a>
  </div>
</div>

<footer class="text-center text-white" style="background-color: #c2e2ec;">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">

      <!-- Instagram -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="https://www.instagram.com/ghina2703_"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="https://www.linkedin.com/in/ghina-nabila-gunawan-bba4b817a/"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-linkedin"></i
      ></a>

      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-dark m-1"
        href="https://github.com/ghina2703/ghina27-app"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <div class="text-center text-dark p-3" style="background-color: #b3dbe7;">
    <p style="font-weight: bold; font-size: 20px;">Sesi terakhir login: {{ last_login }}</p>
    © 2023 Copyright:
    <a class="text-dark" href="http://ghina-nabila21-tugas.pbp.cs.ui.ac.id">Ghina27-app</a>
  </div>
</footer>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-color: #e1f1f5;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .card {
        background-color: #c2e2ec;
        border-color: #d1e9f1;
        width: 400px;
        margin: 0 auto; /* Ini akan menggeser card ke tengah secara horizontal */
    }

    .card-title {
        color: #000;
    }

    .btn-primary {
        background-color: blue;
        border-color: blue;
    }
</style>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="card-title">Register</h1>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="form-group">
                            <input type="submit" name="submit" value="Daftar" class="btn btn-primary">
                        </div>
                    </form>
                    {% if messages %}
                        <ul class="list-unstyled">
                            {% for message in messages %}
                                <li class="text-danger">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}